### ISSUE TITLE
unclear how to run the texnn script

### ISSUE THREAD

**Issue by murphyk** [rrtucci/texnn#1]
Hi. I am not able to use your code in its current form (perhaps due to my ignorance).
I did `git clone https://github.com/rrtucci/texnn.git` and then `pip3 install -e .`  but this gives the error
```
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /Users/kpmurphy/github/texnn
```
I then tried running `python3 asia/asia.py` from the texnn directory but get the error
```
from texnn import *
ModuleNotFoundError: No module named 'texnn'
```

**Comment by murphyk** [comment]
If I copy 'asia.py' to the top level directory where `texnn.py` and `globals.py` live, it all works fine.
But I wanted to avoid polluting the top level with example diagrams.
I suppose PyCharm is adding some directory names to your path ?

**Comment by rrtucci** [comment]
I think so. My impression is that PyCharm does a cd to the top directory
every time you run any python file. I always assume it is going to start
looking at the top directory.

**Comment by murphyk** [comment]
My colleague suggested this way to make things easier for others to use.
- Add `__init__.py` to `texnn` directory.
- Add `setup.py` file (see below) to `texnn` directory 
- Run `python setup.py develop`
- Now anyone can run `python asia/asia.py` from `texnn` directory and it works.

Contents of `setup.py`:
```
NAME = 'texnn'
VERSION = '0.0.1'
if __name__ == '__main__':
    setuptools.setup(
        name=NAME,
        version=VERSION,
        packages=setuptools.find_namespace_packages('texnn'),
    )
```

**Comment by murphyk** [comment]
However, your example scripts also write to the top level directory. So I made this tweak to `asia.py` so it writes to the directory that contains the example script.
```

import pathlib
dir = str(pathlib.Path(__file__).parent.resolve())
name = dir + "/asia"
# ... continues as before
```
